
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-job:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: rm -rf /root/.m2
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'oracle'
        cache: maven
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: |
          ${{ github.workspace }}/backend/target
    - name: Backend Job
      run: cd backend && mvn clean install 
    - name: Restart backend
      run: /root/.nvm/versions/node/v20.7.0/bin/pm2 restart backend
    
  
  frontend-job:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3x
    - name: Set up Node.js
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
        export NVM_DIR=$HOME/.nvm
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install v20.7.0
        nvm use v20.7.0
    - name: Clear npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: cd frontend && npm install
    - name: Debug
      run: |
        ls -la # Check the contents of the current directory
        cd frontend && npm run build
        ls -la # Check the contents after running npm install and npm run build
    - name: Restart frontend
      run: /root/.nvm/versions/node/v20.7.0/bin/pm2 start frontend

